version: '3'

tasks:
  lc:
    desc: Generate code to solve a specific LeetCode problem
    cmds:
      - go run main.go lc {{.CLI_ARGS}}
    silent: true

  commit:
    desc: Commit code for a specific LeetCode problem
    cmds:
      - >-
        git commit -m "chore: add solution for problem #{{.CLI_ARGS}}"
    silent: true

  test:
    desc: Run tests
    cmds:
      - go test -v ./...
    silent: true
